version: 2
jobs:
  one:
    docker:
      - image: ubuntu:18.04
        auth:
    resource_class: 2xlarge
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths:
            - echo-output
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
